### PR TITLE
interp fps multiplier functionality

### LINKED ISSUE #15: Error when setting interp fps to a multiplier
```
Script evaluation failed:
Python exception: could not convert string to float: '4x'

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2982, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2983, in vapoursynth._vpy_evaluate
  File "C:\Users\jackson\Downloads\smoothie-rs-bin-windows\bin\jamba.vpy", line 153, in <module>
    NewNum=float(ip['fps']),
ValueError: could not convert string to float: '4x'

pipe:: Invalid data found when processing input
```

### PR DESCRIPTION
**Pull request by SnowzNZ**
fixes #15

### CODE REVIEW

**Comment by couleurm** [comment]
does isinstance try to convert to the specified type or does it just looks at what it is, because all values are passed as strings per default

**Comment by SnowzNZ** [comment]
It just checks the type

> does isinstance try to convert to the specified type or does it just looks at what it is, because all values are passed as strings per default

It just checks the type

**Comment by couleurm** [comment]
image
dont you gotta cast it? (did you test it)

**Comment by SnowzNZ** [comment]
> image dont you gotta cast it? (did you test it)

what do you mean

**Comment by SnowzNZ** [comment]
oops

**Pull request merged**
