### PR TITLE
Interp masking

### PR DESCRIPTION
**Pull request by SnowzNZ**
s/o atzur

masking example (low input fps to see it in action):
https://medium.afileditch.ch/m3/LmnkFnPuVkHjoOXfCrsL.MP4

### CODE REVIEW

**Comment by couleurm** [comment]
I have un-comitted changes, I will implement this myself, push it and @ you

(if you know better ways to manage git lmk lmao)

I'll keep it open for now

**Comment by animafps** [comment]
> (if you know better ways to manage git lmk lmao)

Rebase

**Comment by couleurm** [comment]
> should we just mask after everything else is done (at the end of the file) and just have a global mask?

that would be the laziest way, everything that isnt mask would have no blur at all

**Comment by SnowzNZ** [comment]
added in https://github.com/couleur-tweak-tips/smoothie-rs/commit/51850b74fa2f0e092851dbbc5e0d38e8579cecc9

**Pull request closed without merging**
