### PR TITLE
Rewrite window.c in Rust

### PR DESCRIPTION
**Pull request by amuseee**
Pretty self explanatory, using the crate `windows-sys` on recommendation from june and aetopia. I don't know if there are any other references to `window.c` that exist in the other files, so the only files that were changed apart from `window.rs` was `Cargo.toml`.

### CODE REVIEW

**Comment by couleurm** [comment]
@aetopia check this out!!

**Comment by Aetopia** [comment]
Replace the relevant `SetConsoleParams` call here: https://github.com/couleur-tweak-tips/smoothie-rs/blob/f04526681aecf6564d5b83f5a7c8d35edeb8bf2f/src/utils.rs#L8

**Comment by amuseee** [comment]
forgot about this for a bit? is the actual `window.rs` file fine? Also I don't think I follow what you're saying about `SetConsoleParams`

**Comment by couleurm** [comment]
yeah the code runs fine but if i ever have a reason to do 100percent rust ill def use it as a starting point

**Pull request closed without merging**
