### PR TITLE
RIFE/model_path fix

### LINKED ISSUE #13: Error while using RIFE/Models
When attempting to use rife I get the following error:
```
ERR:

default_model_dir does not exist, expected: C:\Users\jackson\Downloads\smoothie-rs-bin-windows\models
Script evaluation failed:
Python exception:

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2982, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2983, in vapoursynth._vpy_evaluate
  File "C:\Users\jackson\Downloads\smoothie-rs-bin-windows\bin\jamba.vpy", line 108, in <module>
    raise NotADirectoryError()
NotADirectoryError

pipe:: Invalid data found when processing input
```

When trying to fix this error by adding the `models` folder into `./smoothie-rs-bin-windows`, I receive this error:
```
Script evaluation failed:
Python exception: name 'model_path' is not defined

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2982, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2983, in vapoursynth._vpy_evaluate
  File "C:\Users\jackson\Downloads\smoothie-rs-bin-windows\bin\jamba.vpy", line 111, in <module>
    model_path = path.join(model_path, pi['model'])
NameError: name 'model_path' is not defined

pipe:: Invalid data found when processing input
```

### PR DESCRIPTION
**Pull request by SnowzNZ**
- Added `models` folder to `target`
- Added `rife-v4.4` to `models`
- Updated `shipper.ps1`
- Fixed `model_path` not being defined (fixes #13)

### CODE REVIEW

**Comment by SnowzNZ** [comment]
nevermind this doesnt work 😭

**Comment by SnowzNZ** [comment]
Something about Expr and "+ "

**Comment by couleurm** [comment]
image
hosting binary files on github is a bad idea since .git will keep track of everything

**Comment by couleurm** [comment]
for now you can just set the full path to your smoothie alpha's models dir i guess

**Pull request closed without merging**
